import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Providers } from "./components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JCzyszczon - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='apple-touch-icon'
          href='/apple-icon?<generated>'
          type='image/<generated>'
          sizes='<generated>'
        />
        <link
          rel='icon'
          href='/favicon-32x32?<generated>'
          type='image/<generated>'
          sizes='<generated>'
        />
        <link rel='icon' href='/favicon.ico' sizes='any' />
        <link rel='mask-icon' href='./safari-pinned-tab.svg' color='#d55bd1' />
        <meta name='msapplication-TileColor' content='#2b5797' />
      </head>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
